import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.sass'
import Link from 'next/link';
import Layout, { siteTitle } from '../components/layout';
import { getConfigData } from '../util/config';
import ImageView from '../components/image_view';


const inter = Inter({ subsets: ['latin'] })


export async function getStaticProps() {
  const allConfigData = getConfigData();
  return {
    props: {
      allConfigData,
    },
  };
}


export default function Home({ allConfigData }) {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/help/user-guide">User Guide</Link>
      <ImageView />
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Configuration Files</h2>
        <ul className={utilStyles.list}>
          {allConfigData.map(({ id, data }) => (
            <li className={utilStyles.listItem} key={id}>
              {id}
              <br />
              {data}
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  );
}
